//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyRegister_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class favorite
    {
        public int idFavorite { get; set; }
        public string personWithFavorite { get; set; }
        public string personFavorite { get; set; }
    
        public virtual person person { get; set; }
        public virtual person person1 { get; set; }
    }
}
